services:
  - type: web
    name: dark-host-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
